#!.venv/bin/python3

def mul_3_5(lim):
    sum = 0
    for i in range(1, lim):
        if i % 3 == 0 or i % 5 == 0:
            sum += i
    return sum

def main():
    print("sum of all the multiples of 3 or 5 below 10 = ", mul_3_5(1000))

if __name__ == "__main__":
    main()
